In [183]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [184]:
x_traindf = pd.read_csv('Datasets/Train/x_train.csv')
x_train = np.array(x_traindf)

In [185]:
y_traindf = pd.read_csv('Datasets/Train/y_train.csv')
y_train = np.array(y_traindf)

In [103]:
x_traindf['y']=y_traindf

In [8]:
print(x_train,y_train)

[[332.83]
 [333.87]
 [330.75]
 ...
 [797.86]
 [794.23]
 [785.93]] [[333.87]
 [330.75]
 [328.77]
 ...
 [794.23]
 [785.93]
 [782.78]]


In [41]:
from sklearn.preprocessing import MinMaxScaler

In [97]:
totalDataset = zip(x_train,y_train)

In [102]:
totalDataset = list(totalDataset)
print(len(totalDataset[1]))

2


In [143]:
min_max_scaler = MinMaxScaler()
totalDataset = min_max_scaler.fit_transform(x_traindf)

In [146]:
x_train = []
y_train = []
for i in range(totalDataset.shape[0]):
    x_train.append(totalDataset[i][0])
    y_train.append(totalDataset[i][1])
    

In [147]:
x_train = np.array(x_train)

In [148]:
y_train=np.array(y_train)

In [166]:
x_train = x_train.reshape((1257,1))

In [167]:
print(x_train.shape,y_train.shape)

(1257, 1) (1257,)


In [169]:
def build_timeseries(mat,y_col_index):
    dim_0 = mat.shape[0] - 6
    dim_1=1
    x = np.zeros((dim_0,6,dim_1))
    y = np.zeros((dim_0,))
    
    for i in range(dim_0):
        x[i] = mat[i:6+i]
        y[i] = y_col_index[6+i]
    return x,y

In [170]:
x,y = build_timeseries(x_train,y_train)

In [171]:
print(x.shape,y.shape)

(1251, 6, 1) (1251,)


In [172]:
def trim_dataset(mat, batch_size):
    """
    trims dataset to a size that's divisible by BATCH_SIZE
    """
    no_of_rows_drop = mat.shape[0]%batch_size
    if(no_of_rows_drop > 0):
        return mat[:-no_of_rows_drop]
    else:
        return mat

In [173]:
x_t= trim_dataset(x,32)
y_t = trim_dataset(y,32)

In [174]:
print(x_t.shape)

(1248, 6, 1)


In [175]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *

In [179]:

lstm_model = Sequential()
lstm_model.add(LSTM(100, batch_input_shape=(32, 6,1), dropout=0.0, recurrent_dropout=0.0, stateful=True,     kernel_initializer='random_uniform'))
lstm_model.add(Dropout(0.5))
lstm_model.add(Dense(20,activation='relu'))
lstm_model.add(Dense(1,activation='sigmoid'))
lstm_model.summary()

Model: "sequential_24"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_24 (LSTM)               (32, 100)                 40800     
_________________________________________________________________
dropout_3 (Dropout)          (32, 100)                 0         
_________________________________________________________________
dense_38 (Dense)             (32, 20)                  2020      
_________________________________________________________________
dense_39 (Dense)             (32, 1)                   21        
Total params: 42,841
Trainable params: 42,841
Non-trainable params: 0
_________________________________________________________________


In [180]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['acc'])

In [181]:
model.fit(x_t,y_t,epochs=10,validation_split=0.1)

Train on 1123 samples, validate on 125 samples
Epoch 1/10
1123/1123 [==============================] - 5s 5ms/sample - loss: 0.2521 - acc: 8.9047e-04 - val_loss: 0.8463 - val_acc: 0.0000e+00
Epoch 2/10
1123/1123 [==============================] - 3s 3ms/sample - loss: 0.2521 - acc: 8.9047e-04 - val_loss: 0.8463 - val_acc: 0.0000e+00
Epoch 3/10
1123/1123 [==============================] - 3s 3ms/sample - loss: 0.2521 - acc: 8.9047e-04 - val_loss: 0.8463 - val_acc: 0.0000e+00
Epoch 4/10
1123/1123 [==============================] - 4s 3ms/sample - loss: 0.2521 - acc: 8.9047e-04 - val_loss: 0.8463 - val_acc: 0.0000e+00
Epoch 5/10
1123/1123 [==============================] - 4s 3ms/sample - loss: 0.2521 - acc: 8.9047e-04 - val_loss: 0.8463 - val_acc: 0.0000e+00
Epoch 6/10
1123/1123 [==============================] - 4s 4ms/sample - loss: 0.2521 - acc: 8.9047e-04 - val_loss: 0.8463 - val_acc: 0.0000e+00
Epoch 7/10
1123/1123 [==============================] - 4s 3ms/sample - loss: 0.2521 - ac

In [182]:
print(x_t,y_t)

[[[0.09640129]
  [0.09834351]
  [0.09251685]
  [0.08881917]
  [0.07671765]
  [0.06444805]]

 [[0.09834351]
  [0.09251685]
  [0.08881917]
  [0.07671765]
  [0.06444805]
  [0.06033951]]

 [[0.09251685]
  [0.08881917]
  [0.07671765]
  [0.06444805]
  [0.06033951]
  [0.063589  ]]

 ...

 [[0.97702953]
  [0.97631987]
  [0.97445235]
  [0.97045586]
  [0.9644798 ]
  [0.96632865]]

 [[0.97631987]
  [0.97445235]
  [0.97045586]
  [0.9644798 ]
  [0.96632865]
  [0.96264963]]

 [[0.97445235]
  [0.97045586]
  [0.9644798 ]
  [0.96632865]
  [0.96264963]
  [0.95637477]]] [0.063589   0.05806114 0.06274861 ... 0.95637477 0.95529161 0.96485331]
